appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cW0I0MNAL4Wpl+KNwa/sg8phwnXApAVGMmf2Op33AkB/HS9cg4BRFU7dmxpI6KuMWmSssYcUZYGo4wJYi9eNwj+RSDOFtDACK6MyaENh+n+P03yhNdJVFJ50WV+RGSD9sXwrDdFjYiUB0HsXTFT+diSnZrR7BUTx8KB4x0fRH1GGD5/+txl/LASn7W6LERQ2cpmolMOLUufMaNTiYUOQ8dIrHcf5R40xlQk6oVV+FQFAnwtyBSX6S9iyiMAAoUpLDvT9T7z+pojds+K/RUyALb00zPCWJxE8xR1idQ9X0LjyQfMC53xpkCflctDsht/OkKfT4ROAZLa86Vtl/QByGW8pgm56ux1TYVPjm4Rktgo6wDBoNES7fckC2e9+oF3KiMP956+Unj+U9sVeQn5UukUrRqEWpf6Uyma6LJj2rbKcH1MBVxM8LnybubQSBVtbUr/Jfwrc1Gek+VsjnGFI+Yq7pvpBSgaFgzO/S2VkM7bO25r0XEOtKTbO7ZXiF0EPRmV6KPqb0DLBC1uBVnmBKiP03Qezb7xAPn76Z/KAzCOWjlMd/rUGINLOSmnbMz1G/EsBbhQ7dssGic0wFlK7xu0zCiwMsR7MHMURRyCU8Z2NKiwjKQsKxqS3sZDPGlB/nOIMSQMiMq+n+Q6AUYDczRhmjQ4ZXw9xLcL0kRMnpfQ=}
